const XL='https://cdn.jsdelivr.net/npm/exceljs@4.4.0/dist/exceljs.min.js';
const ZIP='https://cdn.jsdelivr.net/npm/jszip@3.10.1/dist/jszip.min.js';
const H={
 inspection:['ID','Progresiva','Coord. N','Coord. E','Ancho calzada (m)','Ancho carril prom. (m)','Hombro izq. (m)','Hombro der. (m)','Superficie','Estado pavimento','Drenaje','Accesos / intersecciones','Actividad peatonal','Visibilidad','Iluminación','Vegetación / obstáculos','Señalización vertical','Señalización horizontal','Riesgo preliminar','Foto ID','Fecha','Observaciones'],
 vertical:['ID','Progresiva','Coord. N','Coord. E','Sentido','Lado','Grupo','Código señal','Descripción','Existe','Estado físico','Visibilidad','Retroreflectividad aparente','Obstruida','Soporte / poste','Ubicación / montaje','Cumplimiento preliminar','Acción requerida','Prioridad','Foto ID','Observaciones'],
 horizontal:['ID','Prog. inicial','Prog. final','Sentido','Tipo de marca','Color','Ancho (cm)','Longitud (m)','Continuidad','Visibilidad diurna','Visibilidad nocturna','Desgaste estimado (%)','Existe','Estado general','Cumplimiento preliminar','Acción requerida','Prioridad','Foto ID','Observaciones'],
 critical:['ID','Progresiva','Coord. N','Coord. E','Tipo de punto','Usuarios expuestos','Hallazgo / peligro','Causa probable','Exposición (1-3)','Severidad (1-3)','Probabilidad (1-3)','Puntaje','Nivel de riesgo','Evidencia / referencia','Foto ID','Recomendación preliminar','Prioridad'],
 photos:['Foto ID','Nombre de archivo','Fecha','Hora','Progresiva','Coord. N','Coord. E','Sentido / orientación','Componente','Descripción de evidencia','ID relacionado','Observaciones'],
 singular:['ID','Progresiva','Coord. N','Coord. E','Tipo','Descripción','Sentido / lado','Condición','Riesgo asociado','Usuarios afectados','Foto ID','Acción preliminar','Prioridad','Observaciones']
};
function load(src,name){if(window[name])return Promise.resolve();return new Promise((ok,fail)=>{const s=document.createElement('script');s.src=src;s.onload=()=>window[name]?ok():fail(new Error(name));s.onerror=fail;document.head.appendChild(s);});}
async function libs(zip=false){await load(XL,'ExcelJS');if(zip)await load(ZIP,'JSZip');}
const txt=v=>v==null?'':String(v), num=v=>Number.isFinite(Number(v))?Number(v):'';
const norm=v=>txt(v).trim().toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');
const is=(r,t)=>norm(r.type)===norm(t);
const acc=r=>{const n=Number(r.gpsAccuracy??r.accuracy);return Number.isFinite(n)&&n>0?n:null};
const quality=n=>!n?'Sin dato':n<=5?'Excelente':n<=10?'Buena':n<=20?'Aceptable':'Baja';
const method=r=>r.locationMethod==='manual'?'Ajuste manual':'GPS automático';
const fid=r=>`FOTO-${txt(r.id||'SIN-ID').replace(/[^A-Za-z0-9_-]/g,'').replace(/^GC-?/i,'')||'SIN-ID'}`;
const note=r=>[`GeoCampo ID: ${r.id||''}`,r.userName||r.userEmail?`Registrado por: ${r.userName||r.userEmail}`:'',r.locationMethod?`Ubicación: ${method(r)}`:'',acc(r)?`Precisión GPS: ±${acc(r).toFixed(1)} m`:''].filter(Boolean).join(' · ');
const photoName=r=>`${txt(r.id||'registro').replace(/[^A-Za-z0-9_-]/g,'_')}.jpg`;
function rows(records){
 return {
 generic:records.map(r=>[r.id||'',r.date||'',r.time||'',r.createdAt||'',r.userId||'',r.userName||'',r.userEmail||'',num(r.latitude),num(r.longitude),method(r),num(r.gpsLatitude),num(r.gpsLongitude),acc(r)??'',quality(acc(r)),num(r.manualOffsetMeters),r.mapLayer==='street'?'Calles':'Satélite',r.type||'',r.status||'',r.section||'',r.direction||'',r.observation||'',r.syncStatus||'',r.imageUrl||'',fid(r)]),
 inspection:records.filter(r=>is(r,'Condición de vía')).map(r=>[r.id||'',r.section||'',num(r.latitude),num(r.longitude),'','','','','',r.status||'','','','','','','','','','',fid(r),r.date||'',[r.observation||'',note(r)].filter(Boolean).join(' | ')]),
 vertical:records.filter(r=>is(r,'Señal vertical')).map(r=>[r.id||'',r.section||'',num(r.latitude),num(r.longitude),r.direction||'','','','',r.observation||'','Sí',r.status||'','','','','','','','','',fid(r),note(r)]),
 horizontal:records.filter(r=>is(r,'Señal horizontal')).map(r=>[r.id||'',r.section||'','',r.direction||'','','','','','','','','','Sí',r.status||'','','','',fid(r),[r.observation||'',note(r)].filter(Boolean).join(' | ')]),
 critical:records.filter(r=>norm(r.status)==='critico').map(r=>[r.id||'',r.section||'',num(r.latitude),num(r.longitude),r.type||'','',r.observation||'','','','','','','',`GeoCampo ${r.id||''}`,fid(r),'','']),
 photos:records.map(r=>[fid(r),photoName(r),r.date||'',r.time||'',r.section||'',num(r.latitude),num(r.longitude),r.direction||'',r.type||'',r.observation||'',r.id||'',note(r)]),
 singular:records.filter(r=>['dispositivo de seguridad','interseccion','acceso','obra de drenaje','otro'].includes(norm(r.type))).map(r=>[r.id||'',r.section||'',num(r.latitude),num(r.longitude),r.type||'',r.observation||'',r.direction||'',r.status||'','','',fid(r),'','',note(r)])
 };
}
function style(ws,headerRow,headers){
 ws.views=[{state:'frozen',ySplit:headerRow}];
 headers.forEach((h,i)=>{const c=ws.getCell(headerRow,i+1);c.value=h;c.font={name:'Arial',size:9,bold:true,color:{argb:'FFFFFFFF'}};c.fill={type:'pattern',pattern:'solid',fgColor:{argb:'FF2E659C'}};c.alignment={horizontal:'center',vertical:'middle',wrapText:true};ws.getColumn(i+1).width=Math.min(34,Math.max(12,h.length+2));});
 ws.getRow(headerRow).height=34;
 for(let r=headerRow+1;r<=ws.rowCount;r++){ws.getRow(r).eachCell({includeEmpty:true},c=>{c.font={name:'Arial',size:9.5,color:{argb:'FF17324D'}};c.alignment={vertical:'top',wrapText:true};c.border={bottom:{style:'hair',color:{argb:'FFD9E2EB'}}};});}
 if(ws.rowCount>headerRow)ws.autoFilter={from:{row:headerRow,column:1},to:{row:ws.rowCount,column:headers.length}};
}
function sheet(wb,name,title,headers,data,noteText='',headerRow=3){
 const ws=wb.addWorksheet(name);ws.mergeCells(1,1,1,headers.length);const t=ws.getCell(1,1);t.value=title;t.font={name:'Arial',size:14,bold:true,color:{argb:'FFFFFFFF'}};t.fill={type:'pattern',pattern:'solid',fgColor:{argb:'FF0B294C'}};t.alignment={vertical:'middle'};ws.getRow(1).height=28;
 if(noteText){ws.mergeCells(2,1,2,headers.length);const n=ws.getCell(2,1);n.value=noteText;n.font={name:'Arial',size:9,italic:true,color:{argb:'FF66788B'}};n.fill={type:'pattern',pattern:'solid',fgColor:{argb:'FFFFF4D6'}};n.alignment={wrapText:true,vertical:'middle'};ws.getRow(2).height=28;}
 while(ws.rowCount<headerRow-1)ws.addRow([]);ws.addRow(headers);data.forEach(r=>ws.addRow(r));style(ws,headerRow,headers);return ws;
}
function summary(wb,records,R,photoCount=0){const ws=wb.addWorksheet('00_Resumen_Exportacion');ws.columns=[{width:31},{width:22},{width:31},{width:22}];ws.mergeCells('A1:D1');ws.getCell('A1').value='GeoCampo — Exportación para Libro Maestro de Tesis';ws.getCell('A1').font={name:'Arial',size:16,bold:true,color:{argb:'FFFFFFFF'}};ws.getCell('A1').fill={type:'pattern',pattern:'solid',fgColor:{argb:'FF0B294C'}};ws.getRow(1).height=32;ws.mergeCells('A3:D4');ws.getCell('A3').value='Los campos no capturados por GeoCampo se conservan vacíos. No se inventan variables técnicas, cumplimiento normativo ni puntajes de riesgo. La hoja 05 contiene únicamente candidatos marcados como estado Crítico y requiere validación metodológica.';ws.getCell('A3').alignment={wrapText:true,vertical:'top'};ws.getCell('A3').font={name:'Arial',size:10};const A=records.map(acc).filter(Boolean),avg=A.length?(A.reduce((a,b)=>a+b,0)/A.length).toFixed(1):'—';[['Total registros',records.length,'Fotos preparadas',photoCount||records.filter(r=>r.imageUrl||r.photoDataUrl).length],['Precisión GPS promedio',avg==='—'?'Sin dato':`±${avg} m`,'Registros sincronizados',records.filter(r=>r.syncStatus==='synced').length],['02_Inspeccion_100m',R.inspection.length,'03_Senales_Vert',R.vertical.length],['04_Senales_Horiz',R.horizontal.length,'05_Puntos_Criticos',R.critical.length],['06_Registro_Fotos',R.photos.length,'15_Puntos_Singulares',R.singular.length]].forEach(v=>ws.addRow(v));for(let r=6;r<=ws.rowCount;r++)ws.getRow(r).eachCell(c=>{c.font={name:'Arial',size:10};c.border={bottom:{style:'thin',color:{argb:'FFD9E2EB'}}};});ws.views=[{state:'frozen',ySplit:1}];}
function workbook(records,photoCount=0){const wb=new window.ExcelJS.Workbook();wb.creator='GeoCampo';wb.company='Tesis de Ingeniería Civil — El Carrizal';wb.title='GeoCampo — Datos para Libro Maestro';const R=rows(records);summary(wb,records,R,photoCount);const G=['ID','Fecha','Hora','Fecha_hora_ISO','Usuario_UID','Usuario_Nombre','Usuario_Email','Latitud_Final','Longitud_Final','Metodo_Ubicacion','GPS_Latitud_Original','GPS_Longitud_Original','Precision_GPS_m','Calidad_GPS','Ajuste_Manual_m','Capa_Mapa','Tipo','Estado','Tramo_Progresiva','Sentido','Observacion','Estado_Sincronizacion','URL_Fotografia','Foto_ID'];sheet(wb,'01_Registros_Campo','BASE CONSOLIDADA DE REGISTROS GEORREFERENCIADOS — GEOCAMPO',G,R.generic,'Base original de trazabilidad. Conservar antes de distribuir la información en las hojas temáticas.');sheet(wb,'02_Inspeccion_100m','FICHA DE INSPECCIÓN DEL TRAMO CADA 100 m',H.inspection,R.inspection,'GeoCampo solo completa progresiva, coordenadas, estado, fotografía, fecha y observaciones. Las demás variables deben completarse con el instrumento específico.');sheet(wb,'03_Senales_Vert','INVENTARIO Y EVALUACIÓN DE SEÑALIZACIÓN VERTICAL',H.vertical,R.vertical,'Se transfieren ubicación, sentido, estado, evidencia y observación. Código, visibilidad, retroreflectividad, montaje, cumplimiento y prioridad requieren evaluación técnica.');sheet(wb,'04_Senales_Horiz','INVENTARIO Y EVALUACIÓN DE SEÑALIZACIÓN HORIZONTAL',H.horizontal,R.horizontal,'Se transfieren progresiva, sentido, estado y fotografía. Tipo de marca, dimensiones, desgaste, visibilidad y cumplimiento requieren verificación específica.');sheet(wb,'05_Puntos_Criticos','MATRIZ DE PUNTOS CRÍTICOS Y RIESGOS VIALES',H.critical,R.critical,'Solo se preparan candidatos cuyo estado fue marcado Crítico. Exposición, severidad, probabilidad, puntaje y nivel de riesgo quedan vacíos hasta aplicar la metodología aprobada.',4);sheet(wb,'06_Registro_Fotos','REGISTRO FOTOGRÁFICO GEOREFERENCIADO',H.photos,R.photos,'En el paquete ZIP, las fotografías originales se incluyen en la carpeta fotos/.');sheet(wb,'15_Puntos_Singulares','INVENTARIO DE PUNTOS SINGULARES DEL TRAMO',H.singular,R.singular,'Incluye accesos, intersecciones, obras de drenaje, dispositivos de seguridad y registros clasificados como Otro. Riesgo, acción y prioridad requieren análisis posterior.');return wb;}
function dl(blob,name){const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),1000);}
async function photoBlob(r){if(r.photoDataUrl){const x=await fetch(r.photoDataUrl);return x.blob();}if(r.imageUrl){const x=await fetch(r.imageUrl,{mode:'cors',cache:'no-store'});if(!x.ok)throw new Error(`HTTP ${x.status}`);return x.blob();}return null;}
export async function exportThesisWorkbook(records,{onProgress=()=>{}}={}){if(!records?.length)throw new Error('NO_RECORDS');onProgress({stage:'libraries'});await libs();onProgress({stage:'workbook'});const b=await workbook(records).xlsx.writeBuffer();dl(new Blob([b],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'}),`GeoCampo_Para_Libro_Maestro_${new Date().toISOString().slice(0,10)}.xlsx`);return{records:records.length};}
export async function exportThesisPackage(records,{onProgress=()=>{}}={}){if(!records?.length)throw new Error('NO_RECORDS');onProgress({stage:'libraries'});await libs(true);const z=new window.JSZip(),folder=z.folder('fotos'),failed=[];let photos=0;for(let i=0;i<records.length;i++){const r=records[i];onProgress({stage:'photos',current:i+1,total:records.length});try{const b=await photoBlob(r);if(b){folder.file(photoName(r),b);photos++;}else failed.push(`${r.id}\tSin fotografía`);}catch(e){failed.push(`${r.id}\t${e.message}\t${r.imageUrl||''}`);}}onProgress({stage:'workbook'});const x=await workbook(records,photos).xlsx.writeBuffer(),d=new Date().toISOString().slice(0,10);z.file(`GeoCampo_Para_Libro_Maestro_${d}.xlsx`,x);z.file('README_Exportacion.txt',`GEOCAMPO — PAQUETE DE TESIS\n\nRegistros: ${records.length}\nFotografías incluidas: ${photos}\n\nEl Excel contiene hojas compatibles con el Libro Maestro. Los campos no capturados por GeoCampo se dejan vacíos para no inventar información.\n\nLas fotografías originales están en la carpeta fotos/.`);if(failed.length)z.file('fotos_no_recuperadas.txt',failed.join('\n'));onProgress({stage:'zip'});const blob=await z.generateAsync({type:'blob',compression:'DEFLATE',compressionOptions:{level:6}},m=>onProgress({stage:'zip-progress',percent:m.percent}));dl(blob,`GeoCampo_Paquete_Tesis_${d}.zip`);return{records:records.length,photos,missingPhotos:failed.length};}
